(ns autho.database-test
  (:require [clojure.test :refer :all]
            [autho.database :as database]))

(deftest h2-remains-the-default-database
  (with-redefs [database/database-kind (constantly :h2)]
    (is (= "org.h2.Driver" (:classname (database/policy-db))))
    (is (= "h2" (:subprotocol (database/policy-db))))
    (is (= "BIGINT AUTO_INCREMENT PRIMARY KEY" (database/identity-column)))
    (is (= "CLOB" (database/text-column)))))

(deftest postgres-config-requires-an-explicit-url
  (is (thrown? clojure.lang.ExceptionInfo
               ((deref #'database/postgres-spec) nil "autho" "secret"))))

(deftest postgres-dialect-uses-portable-types
  (with-redefs [database/database-kind (constantly :postgres)]
    (is (= {:connection-uri "jdbc:postgresql://localhost:5432/autho"
            :user "autho" :password "secret"}
           ((deref #'database/postgres-spec)
            "jdbc:postgresql://localhost:5432/autho" "autho" "secret")))
    (is (= "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" (database/identity-column)))
    (is (= "TEXT" (database/text-column)))))
