(ns autho.database
  "Database configuration and small SQL-dialect helpers.

   H2 is deliberately the default for local development and existing installs.
   Set AUTHO_DB_KIND=postgres (and AUTHO_DATABASE_URL) to use PostgreSQL."
  (:require [clojure.string :as str])
  (:import (java.sql SQLException)))

(defn database-kind []
  (keyword (str/lower-case (or (System/getenv "AUTHO_DB_KIND") "h2"))))

(defn postgres? [] (= :postgres (database-kind)))
(defn h2? [] (= :h2 (database-kind)))

(defn- h2-spec [path cipher-key]
  (merge {:classname "org.h2.Driver" :subprotocol "h2" :user "sa"}
         (if cipher-key
           {:subname (str path ";CIPHER=AES") :password (str cipher-key " ")}
           {:subname path :password ""})))

(defn- postgres-spec [url user password]
  (when (str/blank? (str url))
    (throw (ex-info "AUTHO_DATABASE_URL is required when AUTHO_DB_KIND=postgres"
                    {:type ::missing-database-url})))
  (cond-> {:connection-uri url}
    (not (str/blank? (str user))) (assoc :user user)
    (some? password) (assoc :password password)))

(defn policy-db []
  (if (postgres?)
    (postgres-spec (System/getenv "AUTHO_DATABASE_URL")
                   (System/getenv "AUTHO_DATABASE_USER")
                   (System/getenv "AUTHO_DATABASE_PASSWORD"))
    (h2-spec (or (System/getenv "AUTHO_POLICY_DB_PATH")
                 (System/getProperty "autho.policy.db.path")
                 "./resources/h2db")
             (System/getenv "H2_POLICY_CIPHER_KEY"))))

(defn audit-db []
  (if (postgres?)
    (postgres-spec (or (System/getenv "AUTHO_AUDIT_DATABASE_URL")
                       (System/getenv "AUTHO_DATABASE_URL"))
                   (or (System/getenv "AUTHO_AUDIT_DATABASE_USER")
                       (System/getenv "AUTHO_DATABASE_USER"))
                   (or (System/getenv "AUTHO_AUDIT_DATABASE_PASSWORD")
                       (System/getenv "AUTHO_DATABASE_PASSWORD")))
    (h2-spec "./resources/auditdb;AUTO_SERVER=TRUE"
             (System/getenv "H2_AUDIT_CIPHER_KEY"))))

(defn identity-column []
  (if (postgres?) "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
      "BIGINT AUTO_INCREMENT PRIMARY KEY"))

(defn text-column [] (if (postgres?) "TEXT" "CLOB"))

(defn unique-violation? [exception]
  (loop [cause exception]
    (cond
      (nil? cause) false
      (and (instance? SQLException cause) (= "23505" (.getSQLState ^SQLException cause))) true
      :else (recur (.getCause ^Throwable cause)))))
